name: bluffing
description: A SEO friendly SSG(Static Site Generator).Includes markdown and tailwind support.
homepage: https://github.com/sanihaq/bluffing
repository: https://github.com/sanihaq/bluffing/tree/main/packages/bluffing

version: 0.1.0

environment:
  sdk: ^3.0.0

topics:
  - bluff
  - seo
  - ssg
  - static site
  - website
  - web
  - html
  - jaspr
  - dsg

dependencies:
  meta: ^1.11.0
  universal_html: ^2.2.4
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.8
